version: "3"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - events_network

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery --app=event_calendar worker -l info
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis
    networks:
      - events_network

  celery-beat:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery --app=event_calendar beat -l info
    volumes:
      - ./:/app/
    env_file:
      - .env
    depends_on:
      - redis
    networks:
      - events_network
  
  redis:
    image: redis:latest
    networks:
      - events_network

networks:
  events_network:
